name: Deploy to GitHub Pages with Firebase

on:
  push:
    branches: ["analysis-page_code"] # Runs on every push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Inject Firebase config as 'firebaseConfig'
      - name: Add Firebase Config
        run: |
          # Escape JSON quotes for JavaScript
          CONFIG_ESCAPED=$(echo '${{ secrets.FIREBASE_CONFIG }}' | sed 's/"/\\"/g')
          # Replace placeholder with <script> tag
          sed -i "s|<!-- FIREBASE_CONFIG -->|<script>const firebaseConfig = $CONFIG_ESCAPED;</script>|g" index.html

      # 3. Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
