name: Stupid, get the API_key need so long time

on:
  push:
    branches: ["AI-assistant_code"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Check if analysis.html exists and print first 10 lines
      - name: Check if analysis.html exists and print first 10 lines
        run: |
          if [ -f page_analysis/analysis.html ]; then
            echo "analysis.html exists!"
            head -n 10 page_analysis/analysis.html
          else
            echo "analysis.html NOT found!"
            exit 1
          fi

      # 3. Inject Firebase config as 'firebaseConfig'
      - name: Add Firebase Config
        run: |
          CONFIG_ESCAPED=$(echo '${{ secrets.FIREBASE_CONFIG }}')
          sed -i "s|<!-- FIREBASE_CONFIG -->|<script>window.firebase_API_key = \"$CONFIG_ESCAPED\";</script>|g" page_analysis/analysis.html
          sed -i "s|<!-- FIREBASE_CONFIG -->|<script>window.firebase_API_key = \"$CONFIG_ESCAPED\";</script>|g" page_food/food.html
          sed -i "s|<!-- FIREBASE_CONFIG -->|<script>window.firebase_API_key = \"$CONFIG_ESCAPED\";</script>|g" page_deepseek/deepseek.html
          sed -i "s|const authtoken = ""|const authtoken = \"${{ secrets.DEEPSEEK_CONFIG }}\"|g" page_deepseek/deepseek.js

      # 4. Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

      # 5. Print the secrets hash
      - name: print the secrets
        run: |
          echo "firebase first"
          echo -n "${{ secrets.FIREBASE_CONFIG }}" | sha256sum
          echo "now deepseek"
          echo -n "${{ secrets.DEEPSEEK_CONFIG }}" | sha256sum
