name: Just get the deeepseek authtoken

on:
  push:
    branches: ["AI-assistant_code"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # This is useless but i just too lazy to delete it
      - name: Check if analysis.html exists and print first 10 lines
        run: |
          if [ -f page_analysis/analysis.html ]; then
            echo "analysis.html exists!"
            head -n 10 page_analysis/analysis.html
          else
            echo "analysis.html NOT found!"
            exit 1
          fi

      # 3. Inject Deepseek config in the stupid var
      - name: Add Deepseek Config
        run: |
          CONFIG_ESCAPED=$(echo '${{ secrets.DEEPSEEK_CONFIG }}')
          sed -i "s|very stupid deepseek authtoken for huggingface|\"$CONFIG_ESCAPED\"|g" page_deepseek/deepseek.js

      # 4. Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

      # 5. Print the secrets hash
      - name: print the secrets
        run: echo -n "${{ secrets.FIREBASE_CONFIG }}" | sha256sum
